platform :ios, '8.0'
use_frameworks!
pod 'AFNetworking', '~> 2.4.0'
pod 'Reachability', '~> 3.0.0'
pod 'KILabel'
pod 'Flurry-iOS-SDK', '~> 7.3'
pod 'CBZSplashView', '~> 1.0'
pod 'FXBlurView', '~> 1.6'
pod 'ALAssetsLibrary-CustomPhotoAlbum', '~> 1.3'
pod 'UzysCircularProgressPullToRefresh', '~> 1.1'
pod 'ABOAuthCore', '~> 0.0'
pod 'Crashlytics', '~> 3.4'
pod 'Fabric', '~> 1.6'
pod 'TwitterKit'
pod 'TwitterCore'